import express from 'express';
import http from 'http';
import cors from 'cors';
import dotenv from 'dotenv';
import path from 'path';
import fs from 'fs';

// Load variables
dotenv.config();

import { connectDB } from './config/db';
import { initRedis } from './config/redis';
import { initSocket } from './services/socketManager';
import { errorHandler } from './middleware/error';
import { authenticateJWT, AuthenticatedRequest } from './middleware/auth';
import Customer from './models/Customer';

// Import Route modules
import authRoutes from './routes/authRoutes';
import orgRoutes from './routes/orgRoutes';
import customerRoutes from './routes/customerRoutes';
import taskRoutes from './routes/taskRoutes';
import chatRoutes from './routes/chatRoutes';
import notificationRoutes from './routes/notificationRoutes';
import analyticsRoutes from './routes/analyticsRoutes';
import auditRoutes from './routes/auditRoutes';

const app = express();
const server = http.createServer(app);

const PORT = process.env.PORT || 5000;

// Connect to Database & Cache
connectDB();
initRedis();

// Initialize Socket.io
initSocket(server);

// Middleware
app.use(cors({
  origin: '*', // Adjust origins in production
  methods: ['GET', 'POST', 'PATCH', 'DELETE', 'PUT', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization'],
}));
app.use(express.json());

// Routes Registry
app.use('/api/auth', authRoutes);
app.use('/api/org', orgRoutes);
app.use('/api/customers', customerRoutes);
app.use('/api/tasks', taskRoutes);
app.use('/api/chat', chatRoutes);
app.use('/api/notifications', notificationRoutes);
app.use('/api/analytics', analyticsRoutes);
app.use('/api/audit-logs', auditRoutes);

// Secure, Isolated File Downloads
app.get('/api/files/download/:filename', authenticateJWT, async (req: AuthenticatedRequest, res: Response | any) => {
  try {
    const { filename } = req.params;
    if (!req.user) {
      return res.status(401).json({ error: 'Unauthorized' });
    }

    // Lookup customer file to verify authorization
    // The filename on disk contains a unique hash generated by Multer
    const customer = await Customer.findOne({
      orgId: req.user.orgId,
      'files.path': { $regex: filename }
    });

    if (!customer) {
      return res.status(403).json({ error: 'Access Denied: You do not have permission to download this file.' });
    }

    const fileMeta = customer.files.find((f: any) => f.path.endsWith(filename));
    if (!fileMeta) {
      return res.status(404).json({ error: 'File metadata not found' });
    }

    if (!fs.existsSync(fileMeta.path)) {
      return res.status(404).json({ error: 'File does not exist on disk' });
    }

    // Send file securely
    res.setHeader('Content-Type', fileMeta.mimeType);
    res.setHeader('Content-Disposition', `attachment; filename="${fileMeta.name}"`);
    const fileStream = fs.createReadStream(fileMeta.path);
    fileStream.pipe(res);
  } catch (error: any) {
    console.error('File download error:', error);
    res.status(500).json({ error: 'Failed to download file' });
  }
});

// Root Route
app.get('/', (req, res) => {
  res.status(200).json({ status: 'TeamCRM API Server is running.', time: new Date() });
});

// Error handling middleware
app.use(errorHandler);

// Start Server
server.listen(PORT, () => {
  console.log(`[Server]: TeamCRM Express server running on port ${PORT}`);
});
